apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      imagePullSecrets:
        - name: acr-auth
      containers:
        - name: currencyservice
          image: registryprodtest.azurecr.io/currencyservice-nonprod:latest
          ports:
            - containerPort: 7000
          env:
            - name: PORT
              value: "7000"
            - name: DISABLE_PROFILER
              value: "1"
          readinessProbe:
            tcpSocket:
              port: 7000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 7000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: nonprod
spec:
  type: ClusterIP
  selector:
    app: currencyservice
  ports:
    - name: grpc
      port: 7000
      targetPort: 7000
      
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: currencyservice
  namespace: nonprod
