apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  namespace: nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      imagePullSecrets:
        - name: acr-auth
      containers:
        - name: shippingservice
          image: registryprodtest.azurecr.io/shippingservice-nonprod:latest
          ports:
            - containerPort: 50051


---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  namespace: nonprod
spec:
  type: ClusterIP
  selector:
    app: shippingservice
  ports:
  - name: http
    port: 50051
    targetPort: 50051
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shippingservice
  namespace: nonprod
